// default package
// Generated 20-oct-2011 14:46:14 by Hibernate Tools 3.4.0.CR1
package py.progweb.fpuna.entidades;
import java.util.HashSet;
import java.io.Serializable; 
import java.util.Set;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caja generated by hbm2java
 */
@Entity
@Table(name = "caja", schema = "public")
public class Caja extends EntidadBase implements Serializable {

	private int idcaja;
	private String descripcion;
	private List<Usuario> usuarios;
	//private List<Pago> pagos;

	public Caja() {
	}

	public Caja(int idcaja) {
		this.idcaja = idcaja;
	}

	/*public Caja(int idcaja, String descripcion, List<Usuario> usuarios,
			List<Pago> pagos) {
		this.idcaja = idcaja;
		this.descripcion = descripcion;
		this.usuarios = usuarios;
		//this.pagos = pagos;
	}*/

	@Id
	@Column(name = "idcaja", unique = true, nullable = false)
	public int getIdcaja() {
		return this.idcaja;
	}

	public void setIdcaja(int idcaja) {
		this.idcaja = idcaja;
	}

	@Column(name = "descripcion", length = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}*/

	/*public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}*/

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public List<Pago> getPagos() {
		return this.pagos;
	}*/

	/*public void setPagos(List<Pago> pagos) {
		this.pagos = pagos;
	}*/
	
	public Object getPK() {
		// TODO Auto-generated method stub
		return this.getIdcaja();
	}

}
