package py.progweb.fpuna.entidades;
// Generated 19-oct-2011 20:14:30 by Hibernate Tools 3.4.0.CR1
import java.io.Serializable;
/*import java.util.HashSet;
import java.util.Set;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;*/

/**
 * Usuario generated by hbm2java
 */


public class Usuario extends EntidadBase implements Serializable {

	private int idusuario;
	//private Caja caja;
	//private Rol rol;
	private String nombreusuario;
	private String nombre;
	private String contrasenha;
	//private List<RolUsuario> rolUsuarios;

	public Usuario() {
	}

	public Usuario(int idusuario, String nombreusuario, String nombre,
			String contrasenha) {
		this.idusuario = idusuario;
		this.nombreusuario = nombreusuario;
		this.nombre = nombre;
		this.contrasenha = contrasenha;
	}

	/*public Usuario(int idusuario, Caja caja, Rol rol, String nombreusuario,
			String nombre, String contrasenha, List<RolUsuario> rolUsuarios) {
		this.idusuario = idusuario;
		this.caja = caja;
		this.rol = rol;
		this.nombreusuario = nombreusuario;
		this.nombre = nombre;
		this.contrasenha = contrasenha;
		this.rolUsuarios = rolUsuarios;
	}*/

	
	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	
	/*public Caja getCaja() {
		return this.caja;
	}*/

	/*public void setCaja(Caja caja) {
		this.caja = caja;
	}*/

	
	/*public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}*/

	
	public String getNombreusuario() {
		return this.nombreusuario;
	}

	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	
	public String getContrasenha() {
		return this.contrasenha;
	}

	public void setContrasenha(String contrasenha) {
		this.contrasenha = contrasenha;
	}

	
	/*public List<RolUsuario> getRolUsuarios() {
		return this.rolUsuarios;
	}

	public void setRolUsuarios(List<RolUsuario> rolUsuarios) {
		this.rolUsuarios = rolUsuarios;
	}*/

	
	public Object getPK() {
		// TODO Auto-generated method stub
		return this.getIdusuario();
	}

}
